Repository openshift/cluster-api-provider-libvirt, pull requests merged in 2018-11, with the labels that each got.

#82 remove log-level option
  Gopkg.lock
  Gopkg.toml
  Makefile
  cmd/manager/main.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE
  vendor/github.com/konsorten/go-windows-terminal-sequences/README.md
  vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/Makefile
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machines.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
  vendor/github.com/sirupsen/logrus/.gitignore
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/hooks/syslog/README.md
  vendor/github.com/sirupsen/logrus/hooks/syslog/syslog.go
  vendor/github.com/sirupsen/logrus/hooks/test/test.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_js.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/terminal_notwindows.go
  vendor/github.com/sirupsen/logrus/terminal_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/node/node.go
Labels: approved, lgtm, size/XXL

#96 Update machine status correctly
  pkg/cloud/libvirt/actuators/machine/actuator.go
Labels: approved, lgtm, size/XS

#88 catch errors and print them
  pkg/cloud/libvirt/actuators/machine/utils/cloudinit.go
  pkg/cloud/libvirt/actuators/machine/utils/domain.go
  test/machines/machines_test.go
Labels: approved, lgtm, size/XS

#95 add command to run e2e
  Makefile
  hack/test-e2e.sh
Labels: approved, lgtm, size/M

#98 Error when timeouted waiting for master machine guest IP
  test/machines/machines_test.go
Labels: approved, lgtm, size/XS

#91 add readme explaining how packet.net provisioning script works
  hack/README.md
Labels: approved, lgtm, size/M

#93 applyMachineStatus: Log changes with ObjectReflectDiff
  pkg/cloud/libvirt/actuators/machine/actuator.go
Labels: approved, lgtm, size/XS

#92 Update packet image
  hack/prebuild/init.sh
  hack/prebuild/main.tf
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
Labels: approved, lgtm, size/S

#86 Allow to specify an ignition configuration through user secret
  examples/ignition-userdata.yml
  examples/ignition.json
  examples/machine-with-userdata.yml
  pkg/apis/libvirtproviderconfig/v1alpha1/libvirtmachineproviderconfig_types.go
  pkg/cloud/libvirt/actuators/machine/actuator.go
  pkg/cloud/libvirt/actuators/machine/utils/domain.go
  pkg/cloud/libvirt/actuators/machine/utils/ignition.go
  tests/actuator/test.go
Labels: approved, lgtm, size/L

#51 Libvirt-actuator bootstrap command
  cmd/libvirt-actuator/README.md
  cmd/libvirt-actuator/main.go
  cmd/libvirt-actuator/resources/init.sh
  cmd/libvirt-actuator/resources/machine.yaml
  examples/machine-with-userdata.yml
  examples/user-data.sh
  examples/userdata.yml
Labels: approved, lgtm, size/XL
