Repository openshift/cluster-api-provider-libvirt, pull requests merged in 2018-09, with the labels that each got.

#8 add linting scripts
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
  hack/yaml-lint.sh
Labels: size/M

#11 use official rh tooling image
  Makefile
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
Labels: lgtm, size/S

#9 Update Dockerfile
  cmd/machine-controller/Dockerfile
Labels: size/S

#10 add libvirt dependency to Makefile
  Makefile
Labels: size/S

#13 ART compatibility
  Dockerfile
  cmd/machine-controller/Makefile
Labels: lgtm, size/S

#15 fix golint issues
  cloud/libvirt/actuators/machine/utils/domain.go
  cloud/libvirt/actuators/machine/utils/volume.go
  cloud/libvirt/providerconfig/register.go
  cloud/libvirt/providerconfig/types.go
  cloud/libvirt/providerconfig/v1alpha1/register.go
  cloud/libvirt/providerconfig/v1alpha1/types.go
Labels: lgtm, size/L

#17 make go vet happy
  cmd/libvirt-actuator/main.go
  cmd/machine-controller/main.go
Labels: lgtm, size/XS

#18 Make tide happy - add owners file
  OWNERS
Labels: lgtm, size/S

#20 add unit test for setCoreOSIgnition
  cloud/libvirt/actuators/machine/utils/domain.go
  cloud/libvirt/actuators/machine/utils/domain_test.go
Labels: approved, lgtm, size/M

#21 Clean Makefile
  Makefile
Labels: approved, lgtm, size/M

#23 actuators/machine: Fix "Coud" -> "Could" typo
  cloud/libvirt/actuators/machine/actuator.go
Labels: approved, lgtm, size/XS

#25 Update README.md
  cmd/libvirt-actuator/README.md
Labels: approved, lgtm, size/XS

#26 make golint more confident
  Makefile
Labels: approved, lgtm, size/XS

#22 add terraform to provision packet machine
  .gitignore
  Makefile
  hack/packet-provision.sh
  hack/prebuild/init.sh
  hack/prebuild/main.tf
  hack/prebuild/variables.tf
Labels: approved, lgtm, size/L
