Repository openshift/cluster-api-provider-libvirt, pull requests merged in 2018-10, with the labels that each got.

#30 Incorporate suggestions from #22
  hack/packet-provision.sh
Labels: approved, lgtm, size/XS

#34 better directory handling in hack/packet-provision.sh
  hack/packet-provision.sh
Labels: approved, lgtm, size/XS

#33 Fix gopath when building the actuator
  Makefile
Labels: approved, lgtm, size/XS

#31 Add console to aid in debugging
  cloud/libvirt/actuators/machine/utils/domain.go
Labels: approved, lgtm, size/S

#40 Initialize rand.Seed to generate random MAC addresses
  cloud/libvirt/actuators/machine/utils/domain.go
Labels: approved, lgtm, size/XS

#27 terraform code for local libvirt testing
  Dockerfile
  hack/prebuild/local-dev/README.md
  hack/prebuild/local-dev/ignition.tf
  hack/prebuild/local-dev/main.tf
  hack/prebuild/local-dev/variables.tf
  hack/prebuild/main.tf
Labels: approved, lgtm, size/L

#38 add actuator binary tests and decouples libvirt utils from machine api
  cloud/libvirt/actuators/machine/actuator.go
  cloud/libvirt/actuators/machine/utils/domain.go
  cloud/libvirt/actuators/machine/utils/ignition.go
  cloud/libvirt/actuators/machine/utils/image.go
  cloud/libvirt/actuators/machine/utils/network.go
  cloud/libvirt/actuators/machine/utils/stream.go
  cloud/libvirt/actuators/machine/utils/volume.go
  cmd/libvirt-actuator/main.go
  cmd/libvirt-actuator/utils/utils.go
  examples/machine-with-full-paths.yaml
  tests/actuator/README.md
  tests/actuator/test.go
Labels: approved, lgtm, size/XXL

#44 Add ssh clients package
  Dockerfile
Labels: approved, lgtm, size/XS

#48 Makefile: cleanup build rule
  Makefile
Labels: approved, lgtm, size/XS

#49 install minikube on packet instance
  hack/prebuild/init.sh
Labels: approved, lgtm, size/S

#50 dump IP address to temporary file
  Makefile
  hack/packet-provision.sh
Labels: approved, lgtm, size/XS

#37 Populate machine status with libvirt domain details
  Dockerfile
  cloud/libvirt/actuators/machine/actuator.go
  cloud/libvirt/actuators/machine/utils/domain.go
Labels: approved, lgtm, size/L

#52 minor cleanup
  Makefile
  boilerplate.go.txt
  hack/packet-provision.sh
Labels: approved, lgtm, size/S

#60 Fix connection leak
  cloud/libvirt/actuators/machine/actuator.go
  cloud/libvirt/actuators/machine/utils/domain.go
Labels: approved, lgtm, size/L

#58 Add libvirt test client
  Gopkg.lock
  test/machines/libvirtclient.go
Labels: approved, lgtm, size/M

#43 Use faster packet instance
  hack/prebuild/main.tf
Labels: approved, lgtm, size/XS

#63 Makefile: add Go debug support to build target
  Makefile
Labels: approved, lgtm, size/XS

#65 Fix minikube version to 0.28.0
  hack/prebuild/init.sh
Labels: approved, lgtm, size/XS

#66 Fix typo
  cmd/libvirt-actuator/README.md
Labels: approved, lgtm, size/XS

#64 Makefile: add machine-controller to build target
  Makefile
Labels: approved, lgtm, size/XS

#69 add tags to instances for easier cleanup
  hack/packet-provision.sh
  hack/prebuild/main.tf
  hack/prebuild/variables.tf
Labels: approved, lgtm, size/XS

#71 Move cloud under pkg/cloud
  Makefile
  cmd/libvirt-actuator/utils/utils.go
  cmd/machine-controller/main.go
  hack/prebuild/main.tf
  pkg/cloud/libvirt/actuators/machine/actuator.go
  pkg/cloud/libvirt/actuators/machine/utils/cloudinit.go
  pkg/cloud/libvirt/actuators/machine/utils/domain.go
  pkg/cloud/libvirt/actuators/machine/utils/domain_test.go
  pkg/cloud/libvirt/actuators/machine/utils/ignition.go
  pkg/cloud/libvirt/actuators/machine/utils/image.go
  pkg/cloud/libvirt/actuators/machine/utils/network.go
  pkg/cloud/libvirt/actuators/machine/utils/stream.go
  pkg/cloud/libvirt/actuators/machine/utils/volume.go
  pkg/cloud/libvirt/providerconfig/doc.go
  pkg/cloud/libvirt/providerconfig/register.go
  pkg/cloud/libvirt/providerconfig/types.go
  pkg/cloud/libvirt/providerconfig/v1alpha1/doc.go
  pkg/cloud/libvirt/providerconfig/v1alpha1/register.go
  pkg/cloud/libvirt/providerconfig/v1alpha1/types.go
  pkg/cloud/libvirt/providerconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/libvirt/providerconfig/zz_generated.deepcopy.go
  test/utils/manifests.go
  tests/actuator/test.go
Labels: approved, lgtm, size/S

#74 change actuator message name
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#76 fix literal
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#75 remove copyright notice
  Dockerfile
  Makefile
  cmd/libvirt-actuator/main.go
  cmd/manager/main.go
  hack/boilerplate.go.txt
  pkg/apis/addtoscheme_libvirtproviderconfig_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/libvirtproviderconfig/group.go
  pkg/apis/libvirtproviderconfig/v1alpha1/doc.go
  pkg/apis/libvirtproviderconfig/v1alpha1/libvirtmachineproviderconfig_types.go
  pkg/apis/libvirtproviderconfig/v1alpha1/register.go
  pkg/apis/libvirtproviderconfig/v1alpha1/v1alpha1_suite_test.go
  pkg/apis/libvirtproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/controller.go
Labels: approved, lgtm, size/L

#79 replace logrus with glog
  cmd/libvirt-actuator/main.go
  cmd/libvirt-actuator/utils/utils.go
  cmd/manager/main.go
  tests/actuator/test.go
Labels: approved, lgtm, size/L

#81 Keep the log-level option temporarily
  cmd/manager/main.go
Labels: approved, lgtm, size/S

#83 Fix fmt script invocation
  Makefile
  pkg/cloud/libvirt/actuators/machine/utils/domain.go
  tests/actuator/test.go
Labels: approved, lgtm, size/XS

#85 Makefile: build machines.test e2e binary
  Makefile
Labels: approved, lgtm, size/XS

#68 Fix machine delete
  pkg/cloud/libvirt/actuators/machine/actuator.go
Labels: approved, lgtm, size/S
