Repository openshift/cluster-api-provider-libvirt, pull requests merged in 2019-02, with the labels that each got.

#112 image: add libvirt-devel package to Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#115 Remove any usage of cluster object in actuator
  pkg/cloud/libvirt/actuators/machine/actuator.go
Labels: approved, lgtm, size/S

#116 Rename labels from sigs.k8s.io to machine.openshift.io
  examples/machine-set.yaml
  examples/machine-with-full-paths.yaml
  examples/machine-with-userdata.yml
  examples/machine.yaml
  pkg/apis/libvirtproviderconfig/v1beta1/libvirtmachineproviderconfig_types.go
Labels: approved, lgtm, size/M

#117 deps: switch cluster-api dependency to use master branch
  Gopkg.toml
Labels: approved, lgtm, size/XS

#118 Update list of owners
  OWNERS
Labels: approved, lgtm, size/XS
