Repository openshift/cluster-api-provider-libvirt, pull requests merged in 2019-04, with the labels that each got.

#133 Dockerfile: Use CentOS base image
  Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#140 Use host-passthrough CPU mode for wokers
  pkg/cloud/libvirt/client/domain.go
Labels: approved, lgtm, size/XS

#146 Revendor github.com/openshift/cluster-api
  Gopkg.lock
  vendor/github.com/openshift/cluster-api/pkg/controller/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/add_machinedeployment.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
Labels: approved, lgtm, size/M

#147 facility field removed in favor of facilities
  hack/prebuild/main.tf
Labels: approved, lgtm, size/XS

#144 Drop volumes full paths
  examples/machine-set.yaml
  examples/machine-with-full-paths.yaml
  examples/machine-with-userdata.yml
  examples/machine.yaml
  pkg/cloud/libvirt/actuators/machine/actuator.go
  pkg/cloud/libvirt/actuators/machine/actuator_test.go
  pkg/cloud/libvirt/actuators/machine/stubs.go
  pkg/cloud/libvirt/client/client.go
  pkg/cloud/libvirt/client/cloudinit.go
  pkg/cloud/libvirt/client/domain.go
  pkg/cloud/libvirt/client/ignition.go
  test/utils/manifests.go
Labels: approved, lgtm, size/L

#148 OWNERS: Add CRC team members
  OWNERS
Labels: approved, lgtm, size/XS
