Repository openshift/cluster-api-provider-libvirt, pull requests merged in 2019-03, with the labels that each got.

#122 report hostname for machine
  pkg/cloud/libvirt/actuators/machine/actuator.go
Labels: approved, lgtm, size/XS

#120 Consistent log messages
  cmd/libvirt-actuator/main.go
  cmd/manager/main.go
  pkg/cloud/libvirt/actuators/machine/actuator.go
  pkg/cloud/libvirt/client/client.go
  pkg/cloud/libvirt/client/cloudinit.go
  pkg/cloud/libvirt/client/domain.go
  pkg/cloud/libvirt/client/ignition.go
Labels: approved, lgtm, size/M

#131 Copy bridge, loopback and host-local to /opt/cni/bin
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/userdata.go
Labels: approved, lgtm, size/XS

#126 Add documentation on hacking on this component
  HACKING.md
Labels: approved, lgtm, ok-to-test, size/M

#124 Record update events
  pkg/cloud/libvirt/actuators/machine/actuator.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/common/consts.go
  vendor/github.com/openshift/cluster-api/pkg/errors/machines.go
Labels: approved, lgtm, size/M

#130 Vendor mockgen under the project and use it under the Makefile target
  Gopkg.lock
  Gopkg.toml
  Makefile
  pkg/cloud/libvirt/client/mock/client_generated.go
Labels: approved, lgtm, ok-to-test, size/M

#127 Remove duplicate upload code
  pkg/cloud/libvirt/client/client.go
  pkg/cloud/libvirt/client/cloudinit.go
  pkg/cloud/libvirt/client/ignition.go
  pkg/cloud/libvirt/client/volume.go
Labels: approved, lgtm, size/L

#132 HACKING: Wait between scaling up & down clusterapi-manager-controllers
  HACKING.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#128 Fetch VM hostname from the DHCP lease
  pkg/cloud/libvirt/actuators/machine/actuator.go
  pkg/cloud/libvirt/client/client.go
  pkg/cloud/libvirt/client/mock/client_generated.go
Labels: approved, lgtm, ok-to-test, size/M

#138 Support different sizes for worker disks
  pkg/cloud/libvirt/client/client.go
Labels: approved, lgtm, size/S

#136 Update example files to providerSpec
  examples/machine-set.yaml
  examples/machine-with-full-paths.yaml
  examples/machine-with-userdata.yml
  examples/machine.yaml
Labels: approved, lgtm, size/XS

#141 verify staleness of vendored cluster-api-actuator-pkg
  Makefile
  hack/verify-actuator-pkg.sh
Labels: approved, lgtm, size/S
