Repository openshift/cluster-api-provider-libvirt, pull requests merged in 2019-08, with the labels that each got.

#165 README: Whitespace fixes
  README.md
Labels: approved, lgtm, size/XS

#168 Bump openshift/cluster-api dependencies
  Gopkg.lock
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machine.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machineset.yaml
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machineset_types.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/sync.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
Labels: approved, lgtm, size/M

#169 HACKING: Update name of cluster API deployment
  HACKING.md
Labels: approved, lgtm, size/S

#170 docs: Syntax hilighting for shell commands
  HACKING.md
  README.md
Labels: approved, lgtm, size/S
