Repository openshift/cluster-api-provider-libvirt, pull requests merged in 2019-07, with the labels that each got.

#162 vendor update kubernetes-drain
  Gopkg.lock
  vendor/github.com/openshift/cluster-api/Gopkg.lock
  vendor/github.com/openshift/cluster-api/Gopkg.toml
  vendor/github.com/openshift/cluster-api/pkg/controller/add_node.go
  vendor/github.com/openshift/kubernetes-drain/drain.go
Labels: approved, lgtm, size/M

#155 Drop the error when the libvirt VM still does not have nic's
  Gopkg.lock
  pkg/cloud/libvirt/actuators/machine/actuator.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
Labels: approved, lgtm, size/M

#157 Cache leases IP's and do not use them on the machine creation
  pkg/cloud/libvirt/actuators/machine/actuator.go
  pkg/cloud/libvirt/actuators/machine/actuator_test.go
  pkg/cloud/libvirt/client/client.go
  pkg/cloud/libvirt/client/domain.go
  pkg/cloud/libvirt/client/mock/client_generated.go
  pkg/cloud/libvirt/client/network.go
Labels: approved, lgtm, size/L

#163 *: remove paulfantom from owners file
  OWNERS
Labels: approved, lgtm, size/XS
