Repository openshift/cluster-api-provider-libvirt, pull requests merged in 2021-11, with the labels that each got.

#230 Bug 2018517: Create event only if the machine was modified
  pkg/cloud/libvirt/actuators/machine/actuator.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#229 Set minimum golang version to 1.16
  go.mod
Labels: lgtm, approved

#225 README: Update libvirt configuration instructions
  README.md
Labels: lgtm, approved, lifecycle/rotten
